# GitHub Secret Scanning Configuration
# This file configures which paths should be excluded from secret scanning

paths-ignore:
  # Package manager files and directories
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - "Pipfile.lock"
  - "poetry.lock"
  - "node_modules/**"
  - "vendor/**"
  
  # Build and output directories
  - "build/**"
  - "dist/**"
  - "out/**"
  - "target/**"
  - ".next/**"
  
  # Documentation and markdown files
  - "docs/**/*.md"
  - "*.md"
  - "README*"
  - "CHANGELOG*"
  
  # Test files and mock data
  - "tests/**"
  - "test/**"
  - "**/*test*"
  - "**/*mock*"
  - "**/*fixture*"
  
  # Configuration files that might contain example secrets
  - "*.example"
  - "*.sample"
  - ".env.example"
  - "config/environments/test.rb"
  
  # Version control and CI/CD directories
  - ".git/**"
  - ".github/workflows/**"
  
  # Add your specific paths here
  # Example: "path/to/your/specific/file.txt"
  # Example: "directory-to-ignore/**"
