name: Admin Team Management
on:
  issues:
    types: [opened, edited]

jobs:
  manage-admin-team:
    if: contains(github.event.issue.labels.*.name, 'admin-request')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh
          
      - name: Configure GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Install action dependencies
        run: |
          cd .github/actions/admin-team-manager
          npm install
          
      - name: Run admin team manager
        uses: ./.github/actions/admin-team-manager
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-app-pem: ${{ secrets.GITHUB_APP_PEM }}
          github-app-id: ${{ secrets.GITHUB_APP_ID }}
          organization: ${{ github.repository_owner }}
          issue-number: ${{ github.event.issue.number }}