name: Demo workflow
on: 
  workflow_dispatch:

jobs:
  build-renan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo
        uses: actions/checkout@v5

      - name: Run my script
        run: echo "My second step"
