name: Test Admin Team Management
on:
  workflow_dispatch:
    inputs:
      user-name:
        description: 'Name of the user to greet'
        required: true
        default: 'World'

jobs:
  test-admin-team:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout current repository (for action)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: current-repo
          
      - name: Checkout .github repository (for admin-team.yml)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository_owner }}/.github
          path: github-repo
          
      - name: Run admin team manager
        uses: ./current-repo/.github/actions/admin-team-manager
        with:
          github-token: ${{ secrets.SUPER_TOKEN }}
          github-app-pem: ${{ secrets.GITHUB_APP_PEM }}
          github-app-id: ${{ secrets.GITHUB_APP_ID }}
          organization: ${{ github.repository_owner }}
          issue-number: ${{ github.event.issue.number }}
          admin-team-repo-path: .github
